# Generated by Django 5.2.8 on 2025-11-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.servico'),
        ),
    ]
