# Generated by Django 5.2.8 on 2025-11-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_agendamento_descricao_agendamento_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.servico'),
            preserve_default=False,
        ),
    ]
