# Generated by Django 5.2.8 on 2025-11-18 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_agendamento_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='password',
            field=models.CharField(default='senhatemporaria123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/4140/4140047.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='professor',
            name='minutos_disponiveis',
            field=models.IntegerField(default=240),
        ),
        migrations.AddField(
            model_name='professor',
            name='password',
            field=models.CharField(default='senhatemporaria123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='preco_hora',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=8),
        ),
    ]
